# Generated by Django 5.1.2 on 2024-10-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_imsj_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imsj',
            name='status',
            field=models.IntegerField(choices=[(1, 'intelect'), (2, 'basis'), (3, 'personal'), (4, 'phisical')]),
        ),
        migrations.AlterField(
            model_name='imsj',
            name='title',
            field=models.CharField(choices=[(1, 'Intelektual'), (2, 'Maxsus tayyorgarlik'), (3, 'Shaxsiy (ruhiy, psixologik)'), (4, 'Jismoniy')], max_length=255),
        ),
    ]
