# Generated by Django 5.1.2 on 2024-10-24 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_imsj_status_alter_imsj_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntelectQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('image', models.ImageField(upload_to='questions/')),
            ],
        ),
        migrations.RemoveField(
            model_name='imsj',
            name='title',
        ),
        migrations.AlterField(
            model_name='imsj',
            name='status',
            field=models.IntegerField(choices=[(1, 'Intelektual'), (2, 'Maxsus tayyorgarlik'), (3, 'Shaxsiy (ruhiy, psixologik)'), (4, 'Jismoniy')]),
        ),
        migrations.CreateModel(
            name='IntelectQuestVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='variants/')),
                ('boolen', models.BooleanField()),
                ('intellect_quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='main.intelectquest')),
            ],
        ),
    ]
