# Generated by Django 5.1.2 on 2024-10-24 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_basisquestvariant_basisquest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basisquestvariant',
            old_name='question',
            new_name='variant',
        ),
    ]
