# Generated by Django 5.1.2 on 2024-10-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_basisquest_basisquests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basisquests',
            name='intellect_quest',
        ),
        migrations.AddField(
            model_name='basisquests',
            name='variants',
            field=models.ManyToManyField(related_name='basis_quests', to='main.basisquestvariants'),
        ),
        migrations.RemoveField(
            model_name='intelectquest',
            name='intellect_quest',
        ),
        migrations.AddField(
            model_name='intelectquest',
            name='intellect_quest',
            field=models.ManyToManyField(related_name='intelekt_quest', to='main.intelectquestvariant'),
        ),
    ]
