# Generated by Django 5.1.2 on 2024-10-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_basisquests_intellect_quest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intelectquest',
            name='intellect_quest',
            field=models.ManyToManyField(related_name='intelekt_quests', to='main.intelectquestvariant'),
        ),
    ]
