# Generated by Django 5.1.2 on 2024-10-25 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_intelekt_maxsus_remove_intelectquest_intellect_quest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intelekt',
            name='savol_matni',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='intelektvariant',
            name='matn',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
    ]
